### ISSUE TITLE
README 中的下載連結不能使用

### ISSUE THREAD

**Issue by andyli** [askme765cs/Wine-QQ-TIM#101]
按下去後的頁面出了這段文字:

> PHP module intl not installed.
> Please ask your server administrator to install the module.
>
> PHP modules have been installed, but they are still listed as missing?
> Please ask your server administrator to restart the web server.

可不可以改用"GitHub Release" 來發佈?

**Comment by askme765cs** [comment]
抱歉，我将核实服务器状况。没有使用github的relase是因为一些原因，在我的网络环境下，上传与下载速度都很不理想。我的一种思路是实现分模块化，自动构建，这样就不需从本地上传，并且可以完成版本持续更新。

**Comment by askme765cs** [comment]
原服务器访问未发现异常
已经将第一个版本上传到release

**Comment by askme765cs** [comment]
谢谢反馈，可以添加群814219978“Wine-QQ-TIM讨论组”来参与具体讨论与测试
未来appimage版本期望实现自动构建与上传到github,sourceforge等平台
