### ISSUE TITLE
Wine-QQ8.9.3 在 X1 Carbon 6th Gen + Ubuntu 16.04 下开启摄像头导致程序崩溃

### ISSUE THREAD

**Issue by tjy137** [askme765cs/Wine-QQ-TIM#109]
软件版本Wine-QQ8.9.3，在X1 Carbon 6th Gen + Ubuntu 16.04 下，打开 设置——声音——开启预览画面 时，摄像头指示灯亮起，但程序会发生崩溃。

**Comment by askme765cs** [comment]
基于wine的QQ/TIM暂时都无法正常使用摄像头，在wine的未来版本或会改观
