### ISSUE TITLE
求个wine-dingding

### ISSUE THREAD

**Issue by Archer456** [askme765cs/Wine-QQ-TIM#114]
求个wine-dingding
感谢大神制作的wine-tim 已经用上了. 但是办公还需要wine-dingding 这钉钉目前公司用的越来越多了也.
万分感谢.

**Comment by shijiantian** [comment]
@Archer456 
https://github.com/nashaofu/dingtalk
有兴趣可以看看这个项目

**Comment by jackyting825** [comment]
> @Archer456
> https://github.com/nashaofu/dingtalk
> 有兴趣可以看看这个项目

这个是基于网页版的,跟Windows下的版本功能上还是相差很多的,还是很希望能出个wine版本的.感谢
