### ISSUE TITLE
Unable to download appimage

### ISSUE THREAD

**Issue by w568w** [askme765cs/Wine-QQ-TIM#122]
The server may have something wrong,it reports a `500 Internal Server Error`.  
```
$ wget https://yun.tzmm.com.cn/index.php/s/XRbfi6aOIjv5gwj
--2018-06-15 09:08:02--  
https://yun.tzmm.com.cn/index.php/s/XRbfi6aOIjv5gwj
正在解析主机 yun.tzmm.com.cn (yun.tzmm.com.cn)... 120.194.87.15
正在连接 yun.tzmm.com.cn (yun.tzmm.com.cn)|120.194.87.15|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 500 Internal Server Error
2018-06-15 09:08:03 错误 500：Internal Server Error。
```
# What have been tried to solve the problem
1. run `curl`(which returned nothing)
2. change proxy
3. use browser(the page is blank)
4. ping `yun.tzmm.com.cn`:
```
$ ping yun.tzmm.com.cn
PING tzmm.com.cn (120.194.87.15) 56(84) bytes of data.

Timeout.
Timeout.
Timeout.
--- tzmm.com.cn ping statistics ---
3 packets transmitted, 0 received, 100% packet loss
```

**Comment by askme765cs** [comment]
See github release v1.0

**Comment by w568w** [comment]
> See github release v1.0

@askme765cs [Here](https://github.com/askme765cs/Wine-QQ-TIM/releases) is no release.
![](https://i.loli.net/2018/06/16/5b2455716bcd4.png)

**Comment by askme765cs** [comment]
Ok now
