### ISSUE TITLE
/home/***/.TIM.unionfs Permission denied

### ISSUE THREAD

**Issue by wisecsj** [askme765cs/Wine-QQ-TIM#123]
无法启动TIM，报 /home/***/.TIM.unionfs Permission denied 错误。

![default](https://user-images.githubusercontent.com/10665384/41919271-a8b5cbaa-7990-11e8-930b-4b7ac935f2fb.png)

![default](https://user-images.githubusercontent.com/10665384/41919326-cfadfc0a-7990-11e8-8ed5-b21944582068.png)

**Comment by askme765cs** [comment]
可以贴一下系统环境与桌面环境

**Comment by sinceow** [comment]
同样的问题
![image](https://user-images.githubusercontent.com/4105018/43299046-4bf74e30-918b-11e8-8e21-29995d941bb1.png)
系统：Ubuntu 18.04  #LTS
桌面：GNOME Shell 3.28.2
#81
