### ISSUE TITLE
Manjaro 上TIM运行良好

### ISSUE THREAD

**Issue by SheezyGuo** [askme765cs/Wine-QQ-TIM#125]
弄了好几天，只有这个运行的情况良好，解决了老大难问题，不用回win发消息收文件了，也不用手机转了

**Comment by wszqkzqk** [comment]
manjaro用我的aur呀https://aur.archlinux.org/packages/deepin.com.qq.office/

**Comment by askme765cs** [comment]
谢谢反馈，可以添加群814219978“Wine-QQ-TIM讨论组”来参与具体讨论与测试
