### ISSUE TITLE
/tmp/.mount_timDISMTN/usr/bin/wine: 没有那个文件或目录

### ISSUE THREAD

**Issue by yaowfhhuc** [askme765cs/Wine-QQ-TIM#128]
after chmod +x TIM-x86_64.AppImage;
when ./TIM-x86_64.AppImage

/tmp/.mount_TIM-x8eeBK3R/AppRun: 行 23: /tmp/.mount_TIM-x8eeBK3R/usr/bin/wine: 没有那个文件或目录
Cleaning up

**Comment by kxhit** [comment]
./TIM-x86_64.AppImage 
/tmp/.mount_TIM-x8yX46iv/AppRun: 行 23: /tmp/.mount_TIM-x8yX46iv/usr/bin/wine: 没有那个文件或目录
Cleaning up

求助！

**Comment by yaowfhhuc** [comment]
我安装了 wine1.6 就好了

**Comment by askme765cs** [comment]
谢谢反馈，可以添加群814219978“Wine-QQ-TIM讨论组”来参与具体讨论与测试
