### ISSUE TITLE
ubuntu18.04 用轻聊版 启动后界面卡死

### ISSUE THREAD

**Issue by Activity00** [askme765cs/Wine-QQ-TIM#129]
用命令行改了权限，然后运行，弹出wine 然后弹出qq界面，输入账号密码出来主界面然后就卡死不动了。甚至切换不到命令行界面只能强制关机。

**Comment by askme765cs** [comment]
谢谢反馈，可以添加群814219978“Wine-QQ-TIM讨论组”来参与具体讨论与测试

**Comment by askme765cs** [comment]
尝试临时解决方法
Ubutnu 18.04中比较简单的解决方法，就是把32库补全。通过以下命令即可安装 sudo apt install libgl1-mesa-glx:i386 libfreetype6:i386 。
