### ISSUE TITLE
Light 版本,无法使用快捷键

### ISSUE THREAD

**Issue by izern** [askme765cs/Wine-QQ-TIM#13]
ctrl+alt+z无法打开新消息窗口,
截图快捷键不能用, 需要焦点在QQ上,才可以使用快捷键

**Comment by leixd1994** [comment]
要求不能太高，哈哈  @zern-king

**Comment by zern-king** [comment]
OK,就想知道是BUG还是其他原因不能实现

**Comment by yinflying** [comment]
@izern http://yinflying.top/2016/09/192

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎试用与反馈
