### ISSUE TITLE
马化腾做不到的 你们做到了 你们太棒了！

### ISSUE THREAD

**Issue by wioi** [askme765cs/Wine-QQ-TIM#130]
如题。你们太棒了！

**Comment by askme765cs** [comment]
谢谢支持。腾讯QQ/TIM是马化腾先生领导的深圳腾讯公司开发的优秀产品，我们的努力只是让其在广大的linux桌面用户上使用更为便利。我们期待着有一天马化腾先生与腾讯公司能够重新重视linux用户，拥抱开源。在这一天实现之前，让更多人免去繁琐，受到便利，是我们的目标。欢迎继续关注项目与参与到项目的完善中来。
