### ISSUE TITLE
Ubuntu 18.04运行出错

### ISSUE THREAD

**Issue by rabbitLove520** [askme765cs/Wine-QQ-TIM#133]
```
/tmp/.mount_TIM-x8mOq2jU/AppRun: 行 23: /tmp/.mount_TIM-x8mOq2jU/usr/bin/wine: 没有那个文件或目录
Cleaning up
```
Ubuntu 18.04.1 LTS

**Comment by askme765cs** [comment]
临时解决方案
Ubutnu 18.04中比较简单的解决方法，就是把32库补全。通过以下命令即可安装 sudo apt install libgl1-mesa-glx:i386 libfreetype6:i386 。 其次，运行时字体有问题，将宋体文件simsun.ttf挎到 $HOME/.DeepinQQ.Appimage/drive_c/windows/Fonts目录下（该目录可自行创建）。

**Comment by rabbitLove520** [comment]
感谢
