### ISSUE TITLE
Thank you very much for QQ Ligth. Perfect

### ISSUE THREAD

**Issue by leixd1994** [askme765cs/Wine-QQ-TIM#14]
![screenshot from 2017-06-16 21-23-11](https://user-images.githubusercontent.com/23328517/27228479-68f36b22-52da-11e7-908d-cb2a2c712bc5.png)

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎试用与反馈
