### ISSUE TITLE
Ubuntu 18.04 无法打开 TIM

### ISSUE THREAD

**Issue by uiosun** [askme765cs/Wine-QQ-TIM#146]
环境：从 Ubuntu 16.04 更换到了 18.04，没有安装 wine。
情况：直接点击 TIM-x86_64.AppImage 没有任何反应

---

很希望本地可以保存聊天记录。该怎么参与到这个项目中，没看到源码什么的。
Ps：我没开发过 `Appimage` 项目，最好来个新手教程，蟹蟹

**Comment by StrayDragon** [comment]
> To run an AppImage, simply:
> **Make it executable**
```bash
$ chmod a+x XXX.AppImage
```
> and **run**!
```bash
$ ./XXX.AppImage
```
试试这样~
文档的话你去看看官网吧: https://appimage.org/

**Comment by uiosun** [comment]
还是不行：

```sh
uiosun@uiosun-CW65S:~/Appliction$ chmod a+x TIM-x86_64.AppImage 

uiosun@uiosun-CW65S:~/Appliction$ ./TIM-x86_64.AppImage 
/tmp/.mount_TIM-x80HDDyt/AppRun: 行 23: /tmp/.mount_TIM-x80HDDyt/usr/bin/wine: 没有那个文件或目录
Cleaning up
```

**Comment by StrayDragon** [comment]
那我就不太清楚了...
我刚刚使用这个方法安上了,你可以尝试这个方法 https://www.jianshu.com/p/23b0d3015db8

**Comment by hundanLi** [comment]
最小化以后怎么重新呼唤出来来？
来自Ubuntu18.04

**Comment by uiosun** [comment]
@hundanLi 
Ubuntu 16.04的时候遇到过，右上角有小图标，但是多次呼唤之后会消失，这个时候需要你 kill 并重启 TIM 文件

**Comment by stringzero** [comment]
有个 AutoInstallWineForUbuntuX64.sh 需要运行下就 不会有 
/tmp/.mount_TIM-x80HDDyt/AppRun: 行 23: /tmp/.mount_TIM-* 这种错

**Comment by StrayDragon** [comment]
@Sun-FreePort @hundanLi 
试试装这个Gnome插件:[TopIcons](https://extensions.gnome.org/extension/495/topicons/)
我的百度云微信什么的都可以直接在top-bar上直接呼出和右键操作.

**Comment by uiosun** [comment]
@Straydragonl 使用 QQ 版本成功启动, 感谢大佬, 我抽空看文档, 最近业余时间在忙着翻译一款开源游戏.

顺带贴上 TIM 报错:

```error
Wine cannot find the FreeType font library.  To enable Wine to use TrueType fonts please install a version of FreeType greater than or equal to 2.0.5.
http://www.freetype.org
```

上述错误重复四次, 出现 clear up, 终止启动操作. (我已经按链接, 下载并编译安装了 2.8 版本的 FreeType)
