### ISSUE TITLE
建议分开版本管理,方便下载

### ISSUE THREAD

**Issue by qidizi** [askme765cs/Wine-QQ-TIM#15]
一般来说,没人会同时使用多个版本,
而多个版本太大了,
建议分开版本存放,
方便下载.
或是提供最新版本,同时提供自动卸载上个版本的脚本.

**Comment by leixd1994** [comment]
我抽空解决这个问题    @qidizi

**Comment by leixd1994** [comment]
尴尬了    Release 好像没法提交合并啊啊    其实在Release发布3个压缩包就可以了 类似这样  

   @askme765cs 
![screenshot from 2017-06-20 09-35-27](https://user-images.githubusercontent.com/23328517/27312693-8d464a16-559c-11e7-9e4f-95b2f55ea5e5.png)

**Comment by askme765cs** [comment]
抱歉才看到^_^我处理一下

**Comment by yomun** [comment]
8.9.2 和 8.9.3 应该分开啦..
每个版本, 一个分支.

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎试用与反馈
新版本上传到国内的服务器上，可以分别下载，而且体积大大减小了，只有200兆左右
