### ISSUE TITLE
TIM-x86_64.AppImage 无法启动 请问下这个问题如何解决呢

### ISSUE THREAD

**Issue by Yakumo-Yukari** [askme765cs/Wine-QQ-TIM#157]
/tmp/.mount_TIM-x8AY4M3w/AppRun:行23: /tmp/.mount_TIM-x8AY4M3w/usr/bin/wine: 没有那个文件或目录 Cleaning up

![2018-10-30 11 55 39](https://user-images.githubusercontent.com/12076232/47694975-e3a11a00-dc3a-11e8-97ee-b024a4ad1b3a.png)

**Comment by lentil1016** [comment]
在我的x86_64 fedora机器上，这个问题是因为没有安装`glibc.i686`造成的，额外的，可能还需要安装`freetype.i686`, `ncurses-compat-libs.i686`，我安装完成以上库之后就可以通过`ps axu|grep TIM`看到主进程在运行了，但很可惜依然没有看到窗口。

**Comment by wang-jinbo** [comment]
chmod了吗

**Comment by Yakumo-Yukari** [comment]
@ustcw0ng 提示信息上看这显然不是权限问题哦，而且我都是直接给的777

**Comment by Quanyu-Mars** [comment]
问题解决了没？

**Comment by caoxuCarlos** [comment]
我也遇到了这个问题，我已经给了执行权限。
运行./TIM-x86_64.AppImage之后，出来一个cleaning up，和 @Yakumo-Yukari 遇到的问题一样，我还没有解决。
