### ISSUE TITLE
TIM 无法运行

### ISSUE THREAD

**Issue by liuyibo123** [askme765cs/Wine-QQ-TIM#158]
fusermount: failed to access mountpoint /home/liuyibo/.TIM.unionfs: Permission denied；
使用root仍然不可以运行

**Comment by CreeperLin** [comment]
同样无法运行
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the ncurses library (libncurses.so.5).
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org
Wine cannot find the FreeType font library.  To enable Wine to
use TrueType fonts please install a version of FreeType greater than
or equal to 2.0.5.
http://www.freetype.org

**Comment by Yakumo-Yukari** [comment]
@CreeperLin  你解决了吗  我运行也是出现这个提示

**Comment by CreeperLin** [comment]
没有 但qq可以运行
我用的是kali linux 4.18

**Comment by jhhuang96** [comment]
我和你一样的问题，ubuntu18.04，无法启动。不知道怎么解决

**Comment by liuyibo123** [comment]
我改用别的了，用的deepin wine tim，亲测可行
[github地址](https://github.com/wszqkzqk/deepin-wine-ubuntu)
![image](https://user-images.githubusercontent.com/18073646/49998783-242cdb00-ffd0-11e8-8d3e-2a70f8a23bf8.png)

**Comment by liuyibo123** [comment]
#close
