### ISSUE TITLE
希望打包成release，clone或者下载都太慢了

### ISSUE THREAD

**Issue by weitaoxin** [askme765cs/Wine-QQ-TIM#16]

**Comment by leixd1994** [comment]
还是学校的网好啊，１００ＭＢ教育网表示无压力　　（＊＾＿＿＾＊）

**Comment by caoxile** [comment]
你只需要下载 master分支 
git clone https://github.com/askme765cs/Wine-QQ.git -b master --single-branch

**Comment by Sundrops** [comment]
分享一个百度云链接 https://pan.baidu.com/s/1qXPJp9a 密码: wf8y

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎试用与反馈
新的版本已经上传到国内的服务器，点击下载链接即可下载
