### ISSUE TITLE
QQ light 经常出现选择表情的界面无法弹出

### ISSUE THREAD

**Issue by leixd1994** [askme765cs/Wine-QQ-TIM#17]
![screenshot from 2017-06-26 11-17-14](https://user-images.githubusercontent.com/23328517/27523638-0a0fed2c-5a61-11e7-8cae-dee33c0bf94b.png)
就是那个笑脸的按钮

**Comment by askme765cs** [comment]
这个问题不是软件的问题而是系统设置的问题，你需要在系统设置中关闭自动把焦点移动到新建窗口上的选项（每一个桌面系统不同，寻找窗口焦点设置的项目）
