### ISSUE TITLE
可不可以打包一下或者丢进AUR

### ISSUE THREAD

**Issue by wszqkzqk** [askme765cs/Wine-QQ-TIM#18]
如图，做一个PKGBUID或者.deb

**Comment by zuohuadong** [comment]
AUR 里有的，还有TIM ～～

但是deb没

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
