### ISSUE TITLE
Arch下输入密码总是提示错误

### ISSUE THREAD

**Issue by LEXUGE** [askme765cs/Wine-QQ-TIM#19]
环境是Arch Linux

**Comment by LEXUGE** [comment]
我每一次用软键盘输入总是说密码错误，可是我是输对的

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
