### ISSUE TITLE
Fonts don't render in QQ

### ISSUE THREAD

**Issue by vadi2** [askme765cs/Wine-QQ-TIM#191]
![image](https://user-images.githubusercontent.com/110988/61592239-f4325f80-abd0-11e9-82fa-3a5278f88053.png)

**Comment by CxZMoE** [comment]
Try installing fakechinese through winetricks.
If that doesn't work,download simun.ttf and put it in the /usr/share/fonts/whatever folder.

**Comment by vadi2** [comment]
> Try installing fakechinese through winetricks.

What is the prefix name?

**Comment by vadi2** [comment]
fakechinese into the default prefix didn't work, but just installing `simun.ttf` helped with a lot of the Chinese font rendering - unfortunately, not English! That is still all boxes.

**Comment by CxZMoE** [comment]
save this as zh.reg and wine it.
`REGEDIT4
[HKEY_LOCAL_MACHINE\Software\Microsoft\Windows NT\CurrentVersion\FontLink\SystemLink]
"Lucida Sans Unicode"="wqy-microhei.ttc"
"Microsoft Sans Serif"="wqy-microhei.ttc"
"Microsoft YaHei"="wqy-microhei.ttc"
"微软雅黑"="wqy-microhei.ttc"
"MS Sans Serif"="wqy-microhei.ttc"
"Tahoma"="wqy-microhei.ttc" 
"Tahoma Bold"="wqy-microhei.ttc"
"SimSun"="wqy-microhei.ttc"
"Arial"="wqy-microhei.ttc"
"Arial Black"="wqy-microhei.ttc"
"宋体"="wqy-microhei.ttc"
"新細明體"="wqy-microhei.ttc"
`

To be sure you have installed wqy-zenhei and wqy-microhei font package.

**Comment by vadi2** [comment]
Thanks - wine in what prefix, the default one?

**Comment by vadi2** [comment]
It works! Thanks a lot. I didn't have to run the registry edit or move any font files: simply installing `wqy-zenhei`, `wqy-microhei` packages, and finding & installing `simun.ttf` did the trick.
