### ISSUE TITLE
楼主的软件非常好用，非常感谢楼主，我给新手发一个详细的安装说明。

### ISSUE THREAD

**Issue by leixd1994** [askme765cs/Wine-QQ-TIM#2]
我的系统使Ubuntu 16.04英文版，附上我详细的安装过程：
首先安装wine-HQ：步骤来自wine官网（https://wiki.winehq.org/Ubuntu）：
打开终端依次运行一下命令（没有前面的数字）：
1：sudo dpkg --add-architecture i386 
2：wget https://dl.winehq.org/wine-builds/Release.key
3：sudo apt-key add Release.key
4：sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
5:sudo apt-get update
6:sudo apt-get install --install-recommends winehq-stable
至此wine-HQ安装完成。
接下来安装winetricks，继续在终端执行一下命令：（步骤来自官网https://wiki.winehq.org/Winetricks）
1：wget  https://raw.githubusercontent.com/Winetricks/winetricks/master/src/winetricks
2：chmod +x winetricks
3：sudo cp winetricks /usr/local/bin

至此所有的准备工作都已经完成，我随后sh qq.sh  配置完文件后QQ并没有启动，重启后再次执行sh qq.sh一切正常，非常完美。

**Comment by leixd1994** [comment]
我的是64位UBuntu  32位Ubuntu系统应该省略  1：sudo dpkg --add-architecture i386 这一步

**Comment by askme765cs** [comment]
感谢你的关于wine和winetricks在ubuntu上的安装教程
@leixd1994 
在arch系统上：终端执行sudo pacman -S wine winetricks可安装最新版wine和winetricks

**Comment by zwithz** [comment]
感谢你的教程，我已经完美使用了，只是有点卡，不管怎么说，谢谢O(∩_∩)O

**Comment by Rnzi** [comment]
您好，我按照您打方法安装，最后一步输入后提示有为满足的依赖关系，求教怎么做。


rnzi@Rnzi-arma:~$ sudo dpkg --add-architecture i386
[sudo] rnzi 的密码： 
rnzi@Rnzi-arma:~$ wget https://dl.winehq.org/wine-builds/Release.key
--2017-10-09 06:12:24--  https://dl.winehq.org/wine-builds/Release.key
正在解析主机 dl.winehq.org (dl.winehq.org)... 151.101.196.69
正在连接 dl.winehq.org (dl.winehq.org)|151.101.196.69|:443... 已连接。
已发出 HTTP 请求，正在等待回应... 200 OK
长度： 3122 (3.0K) [application/pgp-keys]
正在保存至: “Release.key.1”

Release.key.1       100%[===================>]   3.05K  --.-KB/s    in 0s      

2017-10-09 06:12:25 (111 MB/s) - 已保存 “Release.key.1” [3122/3122])

rnzi@Rnzi-arma:~$ sudo apt-key add Release.key
OK
rnzi@Rnzi-arma:~$ sudo apt-add-repository https://dl.winehq.org/wine-builds/ubuntu/
rnzi@Rnzi-arma:~$ sudo apt-get update
命中:1 http://mirrors.yun-idc.com/ubuntu zesty InRelease
命中:2 http://mirrors.yun-idc.com/ubuntu zesty-updates InRelease
命中:3 http://mirrors.yun-idc.com/ubuntu zesty-backports InRelease
命中:4 http://mirrors.yun-idc.com/ubuntu zesty-security InRelease
命中:5 http://archive.canonical.com/ubuntu zesty InRelease                     
命中:6 http://ppa.launchpad.net/wine/wine-builds/ubuntu zesty InRelease        
命中:7 https://dl.winehq.org/wine-builds/ubuntu zesty InRelease
正在读取软件包列表... 完成   
rnzi@Rnzi-arma:~$ sudo apt-get install --install-recommends winehq-stable
正在读取软件包列表... 完成
正在分析软件包的依赖关系树       
正在读取状态信息... 完成       
有一些软件包无法被安装。如果您用的是 unstable 发行版，这也许是
因为系统无法达到您要求的状态造成的。该版本中可能会有一些您需要的软件
包尚未被创建或是它们已被从新到(Incoming)目录移出。
下列信息可能会对解决问题有所帮助：

下列软件包有未满足的依赖关系：
 winehq-stable : 依赖: wine-stable (= 2.0.2~zesty)
E: 无法修正错误，因为您要求某些软件包保持现状，就是它们破坏了软件包间的依赖关系。
rnzi@Rnzi-arma:~$

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎试用与反馈
