### ISSUE TITLE
存在的一些問題。

### ISSUE THREAD

**Issue by AspirinEny** [askme765cs/Wine-QQ-TIM#20]
首先謝謝作者的辛勤付出，大部分功能可以正常使用。
但是我使用過程中發現了有一些不足之處。
我測試的是8.9.3的版本，有以下問題：
1、無法正確退出，退出後QQ.exe、QQProtect.exe依然存在於進程中，退出後需要手動結束相關進程纔可以重新啓動；
2、界面使用的字體是宋體，我在%windows%/fonts目錄下看到的是文泉驛黑體？是否是字體設置不生效，我想設置爲Noto Sans CJK TC，請問應該如何操作？
3、無法記住密碼自動登錄，每次啓動均需要手動輸入密碼。
我的環境是 Archlinux + Gnome 3，Wine的版本是滾動的2.12。
以上。
朧月夜霧起
2017年7月10日 星期一 00:11 EAT

**Comment by yinflying** [comment]
@AspirinEny http://yinflying.top/2016/09/192 参考一下。

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到服务器，点击下载链接即可下载
1.通过禁用一些程式，在新版中这个问题得到了解决
2.可以通过导入注册表的方式解决，新版默认字体即为Noto Sans CJK
3.無法記住密碼自動登錄这个问题暂时还没有解决方案，是wine运行qq的普遍问题
