### ISSUE TITLE
两个链接都打不开

### ISSUE THREAD

**Issue by BoyuGuan** [askme765cs/Wine-QQ-TIM#202]
无论是否挂梯子，两个链接都打不开。
期间打开google、百度都正常

**Comment by halozxc** [comment]
我也是

**Comment by kkkkkong** [comment]
确实打不开

**Comment by Asthestarsfalll** [comment]
确实

**Comment by Vanilla-Yukirin** [comment]
还是没有好？……

**Comment by shyshao** [comment]
可以通过这个链接
[https://sourceforge.net/projects/wine-qq-tim/files/latest/download](url)

**Comment by OmiceyO** [comment]
还是打不开

**Comment by Asthestarsfalll** [comment]
建议使用Icalingua

**Comment by Liuzirui666** [comment]
> 可以通过这个链接 [https://sourceforge.net/projects/wine-qq-tim/files/latest/download](url)

Not working

**Comment by HUGHNew** [comment]
> 可以通过这个链接 [https://sourceforge.net/projects/wine-qq-tim/files/latest/download](url)

这个地址重定向到了<https://github.com/askme765cs/Wine-QQ-TIM/issues/url>这个地址 然而看上去是空的

**Comment by kkkkkong** [comment]
你好，已收到您的邮件！

**Comment by Liuzirui666** [comment]
> > 可以通过这个链接 [https://sourceforge.net/projects/wine-qq-tim/files/latest/download](url)
> 
> 这个地址重定向到了https://github.com/askme765cs/Wine-QQ-TIM/issues/url这个地址 然而看上去是空的

I managed to use deepin, that seems to work so far

**Comment by sanxiadaba** [comment]
还是都打不开，挂上梯子也不行

**Comment by kkkkkong** [comment]
你好，已收到您的邮件！

**Comment by keepgoing365** [comment]
https://sourceforge.net/projects/wine-qq-tim/
这个链接下载可以，亲测可用
