### ISSUE TITLE
存在内存泄露，QQ Light挂机一天没干啥，内存由刚开始的100多M变为490多M

### ISSUE THREAD

**Issue by leixd1994** [askme765cs/Wine-QQ-TIM#22]
存在内存泄露，QQ Light挂机一天没干啥，内存由刚开始的100多M变为490多M

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
