### ISSUE TITLE
gnome-shell下QQ最小化后无法呼唤出来

### ISSUE THREAD

**Issue by lung-zijim** [askme765cs/Wine-QQ-TIM#24]
任务栏的QQ图标不显示，但是占用为一个位置。右键左键的没反应。
基于fcitx的搜狗不能用。我觉得ibus可能没问题。

系统是最广泛的: Ubuntu 16.04 LTS

我还建议作者可以放出个捐款链接哦！

**Comment by askme765cs** [comment]
正在构建的最新版tim在GNOME-shell下测试正常，即将发布
关于无法使用中文输入法：
编辑~/.xprofile
在文件中合适位置添加
export XIM="fcitx" export XIM_PROGRAM="fcitx" export XMODIFIERS="@im=fcitx" export GTK_IM_MODULE="fcitx" export QT_IM_MODULE="fcitx"

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载

**Comment by hundanLi** [comment]
Ubuntu18.04也无法呼唤出来
