### ISSUE TITLE
在fedora26上用wine QQ点击放大图片，图片被聊天框遮住

### ISSUE THREAD

**Issue by chinaluopiao** [askme765cs/Wine-QQ-TIM#26]
在fedora26上用wine QQ点击放大图片，图片被聊天框遮住

![2017-08-03 10-57-42](https://user-images.githubusercontent.com/4196949/28904041-d6f68fd8-77cd-11e7-909d-ae4b97cc8b11.png)

![2017-08-03 10-58-16](https://user-images.githubusercontent.com/4196949/28904030-c48b09f0-77cd-11e7-9048-c1a1ca29f029.png)

请问下 这个有解决方案吗

**Comment by yinflying** [comment]
无，通病。多点两下的事。

**Comment by Blackcorns** [comment]
我点开图片之后，只显示下面一点点，而且图片窗口关不掉

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
