### ISSUE TITLE
Debian(Kali) 如何安装？

### ISSUE THREAD

**Issue by 145287** [askme765cs/Wine-QQ-TIM#28]
使用了描述的安装方法安装后，无法打开，求指点

**Comment by leixd1994** [comment]
直接终端里进入下载的目录，sh qq.sh 看提示啥

**Comment by askme765cs** [comment]
值得注意的一点是，处于安全考虑，wine不允许以root用户运行，请新建普通用户再尝试

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
