### ISSUE TITLE
内存泄露

### ISSUE THREAD

**Issue by TryViva** [askme765cs/Wine-QQ-TIM#29]
偶尔上还好很稳定，上久了内存占用2g多！

**Comment by leixd1994** [comment]
用轻聊版的吧,那个泄露的少,挂一天才600多M

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
