### ISSUE TITLE
QQ light can`t receive File,Waiting Forever & 0.0%Process

### ISSUE THREAD

**Issue by leixd1994** [askme765cs/Wine-QQ-TIM#30]
QQ 8.9.2 8.9.3 may also have the bug
![screenshot from 2017-09-13 10-09-58](https://user-images.githubusercontent.com/23328517/30356498-f39c5b4a-986b-11e7-9564-7bbf768714a6.png)

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
