### ISSUE TITLE
ubuntu 17.04 无法正常运行

### ISSUE THREAD

**Issue by jinyingone** [askme765cs/Wine-QQ-TIM#33]
打开之后,无法收消息就死了

**Comment by jinyingone** [comment]
发现是和remina无法同时运行

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
