### ISSUE TITLE
Linux Mint 安装后无法出现登录窗口

### ISSUE THREAD

**Issue by zuihq** [askme765cs/Wine-QQ-TIM#34]
getsockopt: (10042) Unknown errorgetsockopt: (10042) Unknown errorgetsockopt: (10042) Unknown errorgetsockopt: (10042) Unknown errorwine: cannot find L"C:\\Program Files (x86)\\Tencent\\QQ\\Bin\\TXPlatform.exe"
wine: cannot find L"C:\\Program Files (x86)\\Tencent\\QQ\\Bin\\TXPlatform.exe"
wine: cannot find L"C:\\Program Files (x86)\\Tencent\\QQ\\Bin\\TXPlatform.exe"
getsockopt: (10042) Unknown errorgetsockopt: (10042) Unknown erroruv_client_tcp_init, uv_tcp_open fail, ret=-4094
init server error, err=-4094 addr=127.0.0.1:12291
https_server_init, http_server_init fail

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
