### ISSUE TITLE
实测这个TIM 可以语音，不崩溃～～

### ISSUE THREAD

**Issue by zuohuadong** [askme765cs/Wine-QQ-TIM#35]
上传到了： https://github.com/zuohuadong/myplace/releases/download/0.0.1/TIM1.0.4-for-ubuntu.tar.xz

(仅供学习交流使用)

据说魔改了依赖～

老大方便研究研究么？

**Comment by askme765cs** [comment]
最新版wine-TIM经测试能稳定运行，近期发布

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载

**Comment by zuohuadong** [comment]
断线重连的问题还没解决

**Comment by askme765cs** [comment]
反馈收到 在研究解决办法，欢迎讨论
