### ISSUE TITLE
这个如果要装微信怎么搞的？能加一个吗

### ISSUE THREAD

**Issue by cyoncan** [askme765cs/Wine-QQ-TIM#37]

**Comment by askme765cs** [comment]
在Linux上运行微信已经有相当完善的解决方案，可以安装electronic wechat，功能很完善，也很稳定

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
