### ISSUE TITLE
在askme765cs的基础上最新版的Ｗｉｎｅ ＴＩＭ2.1.0已经制作出，完美运行，本想提交ＭＥｒｇｅ，但考虑到会是仓库变得太大，所以另开了一个．

### ISSUE THREAD

**Issue by leixd1994** [askme765cs/Wine-QQ-TIM#40]
对ａｓｋme765cs表示崇高的敬意
TIM 地址：https://github.com/leixd1994/Wine-TIM-2.1.0

**Comment by askme765cs** [comment]
感谢你的贡献

**Comment by askme765cs** [comment]
感谢你的反馈，最新的基于Appimage版本已经发布，更加强大与便捷，欢迎下载试用
新的版本已经上传到国内的服务器，点击下载链接即可下载
邀请您来完善新的版本与加入到appimage中文社区的本地化工作中来
