### ISSUE TITLE
使用系统浏览器打开链接？

### ISSUE THREAD

**Issue by jemyzhang** [askme765cs/Wine-QQ-TIM#44]
以前crossover下的方法，不知道能不能用于这里
1.更改注册表

>Windows Registry Editor Version 5.00
>
>[HKEY_CLASSES_ROOT\http\shell\open\command]
>@="“C:\windows\system32\winebrowser.exe” -nohome %1"
>
>[HKEY_CLASSES_ROOT\https\shell\open\command]
>@="“C:\windows\system32\winebrowser.exe” -nohome %1"

2. 替换iexplore.exe.so

```
cd /usr/lib/wine/ [crossover: /opt/cxoffice/lib/wine/]
sudo mv iexplore.exe.so iexplore.exe.so.bak
sudo ln -s winebrowser.exe.so iexplore.exe.so
```

**Comment by askme765cs** [comment]
方法2测试可行，感谢你的反馈！
将在新版中修复

**Comment by abcfy2** [comment]
请问新版本什么时候发布？我看目前主页上的链接: http://yun.tzmm.com.cn/index.php/s/5hJNzt2VR9aIEF2

使用的还是IE打开的链接
