### ISSUE TITLE
TIM启动不了

### ISSUE THREAD

**Issue by Kycer** [askme765cs/Wine-QQ-TIM#45]
![scrot_201801131133](https://user-images.githubusercontent.com/14323941/34902406-b9e5df3a-f855-11e7-9c7e-abdd08c8f013.png)

**Comment by Kycer** [comment]
QQ版表情 点不开 不知道是不是 桌面问题 我桌面 i3wm
![scrot_201801131136](https://user-images.githubusercontent.com/14323941/34902422-015023e4-f856-11e7-900c-d3819717df3b.png)

**Comment by askme765cs** [comment]
这个问题不是软件的问题而是系统设置的问题，你需要在系统设置中关闭自动把焦点移动到新建窗口上的选项（每一个桌面系统不同，寻找窗口焦点设置的项目）

**Comment by Kycer** [comment]
恩 可能是我桌面的问题  这个小图标也不显示 但是地方还是占了
![scrot_201801131150](https://user-images.githubusercontent.com/14323941/34902519-04530ca8-f858-11e7-9724-e65c9b179123.png)

**Comment by brady2037** [comment]
Ubuntu16.04，同样报错，尝试把系统自带的wine升级到最新版本就好了
参考：http://blog.csdn.net/wukai_std/article/details/54644868
