### ISSUE TITLE
QQ在Centos7 下无法输入中文

### ISSUE THREAD

**Issue by Humsen** [askme765cs/Wine-QQ-TIM#56]
能够输入英文，就是不能输入中文。请问怎么解决

**Comment by askme765cs** [comment]
这个同样是系统设置的普遍问题
在.xprofile中添加以下

export LC_ALL=zh_CN.UTF-8
export XIM=fcitx  
export XIM_PROGRAM=fcitx
export GTK_IM_MODULE=fcitx
export QT_IM_MODULE=fcitx
export XMODIFIERS="@im=fcitx"



这个设置能解决大部分应用无法使用中文输入法的问题
