### ISSUE TITLE
cannot run appimage in docker

### ISSUE THREAD

**Issue by aaron-yang-biz** [askme765cs/Wine-QQ-TIM#74]
because it requires fuse, howerver cannot enable fuse in docker.

after call --extrace-image, don't know how to start qq. If I use wine qq.exe, then it reports “安全组件...需要重新下载"

**Comment by askme765cs** [comment]
just try this 
https://github.com/bestwu/docker-qq

**Comment by aaron-yang-biz** [comment]
自答，故障已排除。
1. QQ-20171129-x86_64.AppImage要求宿主机必须enable fuse。我通过docker来使用，无法enable fuse（不能以及不愿，安全问题）。通过--appimage-extract展开后得到squashfs_root，该目录下的AppRun不能直接运行
2. 如何修改AppRun。文件里仍然要求加载fuse，所以直接运行会失败。将这一行注释掉。将finish函数中清理fuse挂载的也注释掉
3. 不要用宿主机上的wine（如果有的话）。AppImage自带了wine，因此也要将AppRun中对应行改掉。AppImage中自带的wine路径是squashfs_root/usr/bin
4. 现在运行会提示找不到QQ.exe，因为它会去找c:\program files...而在squashfs_root中，qq的路径是/opt/drive_c/。。。

总之AppImage本身做了一些很tricky的事，如果无法直接从AppIamge运行，而必须解开后运行，你就要对AppRun做一些修改。
