### ISSUE TITLE
无法检测到笔记本内置的摄像头怎么解决？

### ISSUE THREAD

**Issue by yelantf** [askme765cs/Wine-QQ-TIM#76]
如题，是否有解决方案，是不是wine设置的原因...？

**Comment by yelantf** [comment]
emmm....发现能够检测到，但是视频或设置中都无法预览或使用，就是显示不出画面

**Comment by askme765cs** [comment]
目前为止，原生wine不支持tim或qq的视频通话

**Comment by yelantf** [comment]
很悲伤，不是听说deepin的wineqq解决了这个问题吗？

**Comment by askme765cs** [comment]
deepin对wine进行了源码级的优化，所以才有这样的效果
新的版本也会打包deepin的版本，但是一切权力属于deepin,如果deepin公司认为不许可，deepin qq版本随时删除
