### ISSUE TITLE
Manjaro下窗口的中文是无法正常显示

### ISSUE THREAD

**Issue by nb5p** [askme765cs/Wine-QQ-TIM#88]
Manjaro GNOME下窗口标题乱码，应该是缺少字体，如下图。虚拟机安装Ubuntu 16.04.3测试一切正常。
![screenshot from 2018-04-14 23-51-24](https://user-images.githubusercontent.com/2098464/38770118-4ccfd3e6-4040-11e8-98c1-0cd203aa0a97.png)

**Comment by xiaojueguan** [comment]
我也遇到了这个情况

**Comment by yinflying** [comment]
看起来是缺少宋体。
