### ISSUE TITLE
TIM登录问题

### ISSUE THREAD

**Issue by libsgh** [askme765cs/Wine-QQ-TIM#96]
我目前遇到的最大问题就是登录问题
问题1:登录无法记住密码,每次都要手动输入
问题2:不能多开,因为我是多账号,有时候遇到设备锁,扫码后只能登录一个,还有问题1,所以很不方便
问题3:当断网,TIM离线的时候,无法通过选择状态重新登录

**Comment by libsgh** [comment]
还有一个问题,以后还会维护更新吗

**Comment by yinflying** [comment]
密码问题早就是wine QQ的无法解决的问题之一，除非使用deepin QQ. 
最近发现QQ国际版与QQ轻聊版密码文件是一样的，而国际版是可以记住密码的。所以干脆做了一下软链接，当密码失效的时候，就用国际版登一下。

**Comment by YaoLaiGang** [comment]
除了把Tim相关的进程kill外，wine的进程也kill掉好像就可以重新登录了，这个退出是不会kil进程的

**Comment by yinflying** [comment]
呃，理论上QQ进程退出了，wine进程也会退出的。（如果不是这样，说明包有问题）

**Comment by YaoLaiGang** [comment]
@yinflying 应该是叫wineserver，我的操作系统是Ubuntu18.04，可能不大一样，但我确实是这么解决的

**Comment by askme765cs** [comment]
@libsgh 对这个项目完善的尝试一直在进行，但是因为学业因素，这个项目的进展遇到一些阻碍。我不会放弃对项目的维护，但是到所谓完美的程度，不会是一个很快的过程。更新迟缓的另一个原因问题的复杂度比我预期的高，甚至同一个系统在更新前后的表现都有差异，更不用说在不同系统，不同版本，不同桌面环境之间。小的改动可能解决问题，也可能制造出新的问题。我在寻找一种可行的强大的框架，来解决这个问题。

**Comment by askme765cs** [comment]
@libsgh 问题1是目前利用wine的 qq/TIM（包括deepin.qq/tim）的通病，暂时还没有解决方案。
问题2 这个与appimage的实现机制有关，它运行时在/tmp里生成的文件具有排他性，所以多个同时运行就会起冲突。我会尝试与appimage的维护者沟通解决这个问题的方法
问题3 这个问题也是这个版本的普遍问题，原因正在寻找。

**Comment by yinflying** [comment]
@askme765cs 第三个问题和第一个问题是相关的。如果密码能记住，那么就可以断线重连了。
楼主的精神是不错，但是也得注意着呢，为QQ花费太大心力是不太可取的，毕竟是一个完全不支持linux的闭源软件，而且一直处理更新状态，而QQ的使用状态往往和wine的实现程度有着相当的关系的。

同一个系统更新前后存在差异也是正常现像，毕竟wine的依赖比较多，即便APP image 能够解决部分包的依赖问题，但是总不能把整个系统给打包起来吧？
APPimage 虽然是一个解决方案，但是从个人角度来看，并不能解决问题。

另外，题主你所面的是很多新手，在描述问题和解决问题上的能力上存在较大的问题，也会带来一些困扰。（老手要么不用qq，要么已经能熟练的使用wine了）不管怎么，此处贴上鄙人的wineQQ的经验吧，仅供老手参考: http://yinflying.top/2016/09/192

**Comment by libsgh** [comment]
@yinflying @YaoLaiGang 感谢两位的帮助，虽然没能解决问题，我心里是非常不愿意用wine的，但是QQ实在是工作需要，目前确实没有完美的方案，deepin的QQ比较好，但是实在不喜欢这个系统，因为经常的卡死，你说第一个问题和第三个问题是关联的，断线重连报的是防火墙的一个错误，我并不确定是不是密码问题，第二个按照你们说是APPimage本身的问题
